name: release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/master' }}
    environment: release
    permissions:
       id-token: write
    steps:
    - name: Install packaging dependencies
      run: pip install build
    - uses: actions/checkout@v4
    - name: sed version
      run: |
        echo "Got version from vcs: ${{ github.ref_name }}"
        sed -i 's/version = \"0.0.0\"/version = \"${{ github.ref_name }}\"/' pyproject.toml
        cat pyproject.toml | grep -i version
    - name: Build package
      run: python -m build
    - name: Publish package to real PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


  docs:
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install doc dependencies
        run: pip install -r dev_docs/requirements.txt
      - run: |
          mkdocs gh-deploy --force
