name: release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/master' }}
    environment: release
    permissions:
       id-token: write
    steps:
    - name: Install packaging dependencies
      run: pip install build
    - uses: actions/checkout@v5
    - name: sed version
      run: |
        echo "Got version from vcs: ${{ github.ref_name }}"
        sed -i 's/version = \"0.0.0\"/version = \"${{ github.ref_name }}\"/' pyproject.toml
        cat pyproject.toml | grep -i version
    - name: Build package
      run: python -m build
    - name: Publish package to real PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


  docs:
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true
          python-version: "3.12"
      - run: uv run --no-project --with-requirements dev_docs/requirements.lock -- mkdocs gh-deploy --force
